version: '3'
services:
  dev:
    image: neibrs/isp:dev
    container_name: isp_dev
    extra_hosts:
      - "dockerhost:192.168.1.142"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      PHP_IDE_CONFIG: serverName=laradock
    volumes:
      - ./isp_dev/services/config/httpd.conf:/etc/apache2/httpd.conf
      - ./isp_dev/services/config/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - isp-dev-unison-sync:/var/www/html
    ports:
      - 88:80
    entrypoint: isp_dev/entry.sh
volumes:
  isp-dev-unison-sync:
    external: true